mysite/blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    # /blog/
    path('', views.PostLV.as_view(), name='index'),

    # /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # /blog/post/slug-exam/
    # 한국어 처리를 위한 re_path 및 패턴
    # path('post/<slug:slug>/', views.PostDV.as_view(), name='post_detail'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # /blog/archive/2020/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # /blog/archive/2020/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # /blog/archive/2020/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='archive_today_archive'),
]

mysite/bookmark/urls.py
from django.urls import path

from bookmark import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    path('admin/', admin.site.urls),

    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    # class-based views
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

mysite/bookmark/models.py
from django.db import models

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title

mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from blog.models import Post

class PostLV(ListView):
    model = Post
    paginate_by = 2


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

mysite/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from bookmark.models import Bookmark

class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

mysite/templates/blog/post_archive.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Blog Post Archive</title>
</head>
<body>
    <h1>Post Archive until {% now "N d, Y" %}</h1>

    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                {{ date|date:"Y" }}
            </a>
        </li>
        {% endfor %}
    </ul>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/templates/blog/post_archive_day.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Blog Post Archive Day</title>
</head>
<body>
    <h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/templates/blog/post_archive_month.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Blog Post Archive Month</title>
</head>
<body>
    <h1>Post Archive for {{ month|date:"N Y" }}</h1>

    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'b' date|date:'d' %}">
                {{ date|date:"Y" }}-{{ date|date:"b" }}-{{ date|date:"d" }}
            </a>
        </li>
        {% endfor %}
    </ul>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/templates/blog/post_archive_year.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Blog Post Archive Year</title>
</head>
<body>
    <h1>Post Archive for {{ year|date:"Y" }}</h1>

    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}">
                {{ date|date:"Y" }}-{{ date|date:"b" }}
            </a>
        </li>
        {% endfor %}
    </ul>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/templates/blog/post_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Blog Post Detail</title>
</head>
<body>
    <h1>{{ object.title }}</h1>

    <p>
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous Post">
            &laquo;- {{ object.get_previous }}
        </a>
        {% endif %}

        {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}", title="View next Post">
            {{ object.get_next }} -&raquo;
        </a>
        {% endif %}
    </p>
    <p>
        {{ object.modify_dt|date:"j F Y" }}
    </p>
    <br>

    <div>
        {{ object.content|linebreaks }}
    </div>
</body>
</html>

mysite/templates/blog/post_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Blog Post List</title>
</head>
<body>
<h1>Post List</h1>

{% for post in object_list %}
    {# <h3><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h3> #}
    <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
    {{ post.modify_dt|date:"N d, y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
        {% endif %}
    </span>
</div>

</body>
</html>

mysite/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Bookmark Detail</title>
</head>
<body>
    <div id="content">
        <h1>Bookmark Detail {{ object.title }}</h1>
        <ul>
        <li><a href="{{ object.url }}">{{ object.url }}</a></li>
        </ul>
    </div>
</body>
</html>

mysite/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Bookmark List</title>
</head>
<body>
    <div id="content">
        <h1>Bookmark List</h1>

        <ul>
            {% for bookmark in object_list %}
                <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>